import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "CHUDI",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Chudi, the vibrant and jingling bangles, add a touch of cultural charm to every Indian ensemble.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "chudi",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Chudi, the vibrant and jingling bangles, add a touch of cultural charm to every Indian ensemble.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Maxi Wear",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Elevate your wardrobe with maxiwear – the epitome of relaxed elegance, offering versatility and flair.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Princess Dress",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "The princess dress, adorned with sparkling sequins and layers of tulle, transforms dreams into reality.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product16_662e25ad-631f-4684-bd09-96b6eabf2672_600x.jpg?v=1532433836",
    productName: "spicy veggie cheese",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Maxiwear brings comfort and style together with long, graceful silhouettes perfect for any occasion.",
  },
  {
    _id: 1002,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product2_600x.jpg?v=1532430654",
    productName: "pepproni pizza",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "These exquisite chudi bangles, with their intricate designs and vibrant hues, are a symbol of tradition and beauty in Indian fashion.",
  },
  {
    _id: 1003,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/p1_58040b1d-ce8a-473f-815e-79800255367a_600x.jpg?v=1532433737",
    productName: "spicy vegetable pizza",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Our collection of women's dresses combines fashion-forward styles with unparalleled comfort, ensuring you look and feel your best for any occasion.",
  },
  {
    _id: 1004,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product7_a9f21577-4e2e-429a-b708-74a0eeb6e40d_600x.jpg?v=1532434070",
    productName: "veggie chicken cheese",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Her dress, a stunning blend of lace and chiffon, exuded timeless elegance and made her the epitome of grace and style.",
  },
  {
    _id: 1005,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product7_600x.jpg?v=1532428956",
    productName: "chicken supreme pizza",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Her dress, a stunning blend of lace and chiffon, exuded timeless elegance and made her the epitome of grace and style.",
  },
  {
    _id: 1006,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product13_7c4d420f-8b77-4c4e-94ba-1f2ac88fc00e_600x.jpg?v=1532434341",
    productName: "country pizza",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "Her dress, a stunning blend of lace and chiffon, exuded timeless elegance and made her the epitome of grace and style.",
  },
  {
    _id: 1007,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product27_02f6cfed-65e9-40ed-ab37-b4986bff82e8_600x.jpg?v=1532433900",
    productName: "chicken tikka pizza",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Her dress, a shimmering mosaic of sequins and beads, sparkled like a thousand stars on a moonless night.",
  },
  {
    _id: 1008,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product27_02f6cfed-65e9-40ed-ab37-b4986bff82e8_600x.jpg?v=1532433900",
    productName: "country feast pizza",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "The dress, a vision in pure white, flowed like a waterfall of silk, capturing every eye in the room.",
  },
  {
    _id: 1009,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product14_93ad183a-d4dd-4b7d-99b8-8ad7374aaf22_600x.jpg?v=1532433958",
    productName: "chicken double cheese",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "The dress she wore was a masterpiece of design and craftsmanship. It cascaded in elegant waves of satin, the deep midnight blue fabric catching the light with every step she took.",
  },
  {
    _id: 1010,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product14_93ad183a-d4dd-4b7d-99b8-8ad7374aaf22_600x.jpg?v=1532433958",
    productName: "chicken veggie cheese",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "The dress was an exquisite shade of deep emerald, adorned with intricate lace detailing.",
  },
  {
    _id: 1011,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product14_93ad183a-d4dd-4b7d-99b8-8ad7374aaf22_600x.jpg?v=1532433958",
    productName:"chicken tikka pizza",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "This is a European traditional dress originally worn by peasants there;The dress has an apron with lacing on the back or front.",
  },
  {
    _id: 1012,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product16_662e25ad-631f-4684-bd09-96b6eabf2672_600x.jpg?v=1532433836",
    productName: "pepproni pizza",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "A close fitting dress usually ending near the knee. Usually there will be a slit in the back so that you can walk comfortably.",
  },
  {
    _id: 1013,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product39_600x.jpg?v=1532429707",
    productName: "Chudi",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "A close fitting dress usually ending near the knee. Usually there will be a slit in the back so that you can walk comfortably.    .",
  },

  {
    _id: 1014,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product7_600x.jpg?v=1532428956",
    productName: "chicken tikka pizza",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "This is a loose fitting dress with the skirt seam being somewhere near the hip rather than at the waist length.",
  },
  {
    _id: 1015,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product7_600x.jpg?v=1532428956",
    productName: "Cheese Tomato Pizza",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "This is a loose fitting dress with the skirt seam being somewhere near the hip rather than at the waist length.",
  },
  {
    _id: 1016,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product13_7c4d420f-8b77-4c4e-94ba-1f2ac88fc00e_600x.jpg?v=1532434341",
    productName: "Princess Steam Dress",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "This kind of dress resembles a shirt in the top portion, with a collar and an open front button placket.",
  },
  {
    _id: 1017,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/p2_a294897c-03de-4292-8da9-a81cb235c5b6_600x.jpg?v=1532430779",
    productName: "Mini pizza",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "This kind of dress resembles a shirt in the top portion, with a collar and an open front button placket.",
  },
  {
    _id: 1018,
    img: "https://momodesigns.in/html/domnoo/web/images/img3.png",
    productName: "Cheese Tomato Pizza",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "This kind of dress resembles a shirt in the top portion, with a collar and an open front button placket.",
  },
  {
    _id: 1019,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product33_fa220693-cfc1-43d3-8bf2-7bf848a58f9d_600x.jpg?v=1532431858",
    productName: "Grilled chicken sandwich",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "This is a style of dress with an Asymmetrical closing. This  dress usually has one side wrapped over the other side and usually has a tie which closes the front opening.",
  },
  {
    _id: 1020,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/p2_a294897c-03de-4292-8da9-a81cb235c5b6_600x.jpg?v=1532430779",
    productName: "chicken Alfredo",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "This is a style of dress with an Asymmetrical closing. This  dress usually has one side wrapped over the other side and usually has a tie which closes the front opening.",
  },
  {
    _id: 1021,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product5_0204f719-ac69-4ecd-9c28-151b8adb4856_600x.jpg?v=1532433589",
    productName: "chicken pizza",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "This is a dress originally worn by the peasants in Europe, with raglan sleeves or very loose sleeves.",
  },
  {
    _id: 1022,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product7_aaa4d0e6-416c-41f8-b42e-468d8a67cfae_600x.jpg?v=1532431688",
    productName: "chicken tikka pizza",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "This is a dress originally worn by the peasants in Europe, with raglan sleeves or very loose sleeves.",
  },
  {
    _id: 1023,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product5_0204f719-ac69-4ecd-9c28-151b8adb4856_600x.jpg?v=1532433589",
    productName: "country feast pizza",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "This is a dress originally worn by the peasants in Europe, with raglan sleeves or very loose sleeves.",
  },
  {
    _id: 1024,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/p2_a294897c-03de-4292-8da9-a81cb235c5b6_600x.jpg?v=1532430779",
    productName: "chicken bacon ranch pizza",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "This refers to a tight fitting body hugging dress made of a stretchy fabric. It usually ends near or above the knee.",
  },
  {
    _id: 1025,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product5_0204f719-ac69-4ecd-9c28-151b8adb4856_600x.jpg?v=1532433589",
    productName: "Philly steak pizza",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "This refers to a tight fitting body hugging dress made of a stretchy fabric. It usually ends near or above the knee.",
  },
  {
    _id: 1026,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/p2_a294897c-03de-4292-8da9-a81cb235c5b6_600x.jpg?v=1532430779",
    productName: "cheeseBurger pizza",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "This refers to a tight fitting body hugging dress made of a stretchy fabric. It usually ends near or above the knee.",
  },
  {
    _id: 1027,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product29_a4a92191-927d-415b-9248-6144248727f3_600x.jpg?v=1532433682",
    productName:"chicken tikka pizza",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "This is a dress that has a fitted bodice and a very flared circular skirt. They have an Aline silhouette with a very defined waist.",
  },
  {
    _id: 1028,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product7_aaa4d0e6-416c-41f8-b42e-468d8a67cfae_600x.jpg?v=1532431688",
    productName: "Haiiwan pizza",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "This is a dress that has a fitted bodice and a very flared circular skirt. They have an Aline silhouette with a very defined waist.",
  },
  {
    _id: 1029,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product29_a4a92191-927d-415b-9248-6144248727f3_600x.jpg?v=1532433682",
    productName: "Mushroom pizza",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "This is a dress that has a fitted bodice and a very flared circular skirt. They have an Aline silhouette with a very defined waist.",
  },
  {
    _id: 1030,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/p2_a294897c-03de-4292-8da9-a81cb235c5b6_600x.jpg?v=1532430779",
    productName: "veggie cheese pizza",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "A granny dress is a loose fitting dress with long sleeves. This dress usually has ruffles or flounces and a high collar.",
  },
  {
    _id: 1031,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product29_a4a92191-927d-415b-9248-6144248727f3_600x.jpg?v=1532433682",
    productName: "veggie love",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "A granny dress is a loose fitting dress with long sleeves. This dress usually has ruffles or flounces and a high collar.",
  },
  {
    _id: 1032,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product7_aaa4d0e6-416c-41f8-b42e-468d8a67cfae_600x.jpg?v=1532431688",
    productName: "Avacado pizza",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "A granny dress is a loose fitting dress with long sleeves. This dress usually has ruffles or flounces and a high collar.",
  },
  {
    _id: 1033,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/p2_a294897c-03de-4292-8da9-a81cb235c5b6_600x.jpg?v=1532430779",
    productName: "Meat feast pizza",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "This is a full length dress with a flared cut narrowing down to a narrower hem. It is usually made in a flowy fabric.",
  },
  {
    _id: 1034,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product7_aaa4d0e6-416c-41f8-b42e-468d8a67cfae_600x.jpg?v=1532431688",
    productName: "chicken tikka pizza",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "This is a full length dress with a flared cut narrowing down to a narrower hem. It is usually made in a flowy fabric",
  },
  {
    _id: 1035,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/p2_a294897c-03de-4292-8da9-a81cb235c5b6_600x.jpg?v=1532430779",
    productName: "BBQ chicken pizza",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "This is a full length dress with a flared cut narrowing down to a narrower hem. It is usually made in a flowy fabric.",
  },
  {
    _id: 1036,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product29_a4a92191-927d-415b-9248-6144248727f3_600x.jpg?v=1532433682",
    productName: "Four cheese pizza",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "This is a full length dress with a flared cut narrowing down to a narrower hem. It is usually made in a flowy fabric.",
  },
  {
    _id: 1037,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product7_aaa4d0e6-416c-41f8-b42e-468d8a67cfae_600x.jpg?v=1532431688",
    productName: "Garlic shrmip",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "This is a full length dress with a flared cut narrowing down to a narrower hem. It is usually made in a flowy fabric",
  },
  {
    _id: 1038,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product7_aaa4d0e6-416c-41f8-b42e-468d8a67cfae_600x.jpg?v=1532431688",
    productName: "veggie love",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "This is a full length dress with a flared cut narrowing down to a narrower hem. It is usually made in a flowy fabric",
  },
  {
    _id: 1039,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product29_a4a92191-927d-415b-9248-6144248727f3_600x.jpg?v=1532433682",
    productName: "chicken tikka pizza",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "This is a full length dress with a flared cut narrowing down to a narrower hem. It is usually made in a flowy fabric.",
  },
  {
    _id: 1040,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product9_600x.jpg?v=1532430203",
    productName: "veggie feast pizza",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "This is a full length dress with a flared cut narrowing down to a narrower hem. It is usually made in a flowy fabric.",
  },
  {
    _id: 1041,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product13_7c4d420f-8b77-4c4e-94ba-1f2ac88fc00e_600x.jpg?v=1532434341",
    productName: "pepproni pizza",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A  trumpet dress has a fitted bodice till the knee or just below the knee  where it flares to the hem.",
  },
  {
    _id: 1042,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product13_7c4d420f-8b77-4c4e-94ba-1f2ac88fc00e_600x.jpg?v=1532434341",
    productName: "veggie love",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "A  trumpet dress has a fitted bodice till the knee or just below the knee  where it flares to the hem.",
  },
  {
    _id: 1043,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/p2_a294897c-03de-4292-8da9-a81cb235c5b6_600x.jpg?v=1532430779",
    productName: "Tandoori tikka",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "A  trumpet dress has a fitted bodice till the knee or just below the knee  where it flares to the hem.",
  },
  {
    _id: 1044,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product13_7c4d420f-8b77-4c4e-94ba-1f2ac88fc00e_600x.jpg?v=1532434341",
    productName: "veggie feast pizza",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "A  trumpet dress has a fitted bodice till the knee or just below the knee  where it flares to the hem.",
  },
  {
    _id: 1045,
    img: "https://the-pizza-home.myshopify.com/cdn/shop/products/product9_600x.jpg?v=1532430203",
    productName: "chicken pizza",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Apron dress is a sleeveless dress with a bib and a skirt attached to it just like an apron.",
  },
  // {
  //   _id: 1046,
  //   img: "https://www.google.co.in/url?sa=i&url=https%3A%2F%2Fwww2.hm.com%2Fen_in%2Fproductpage.1129349001.html&psig=AOvVaw3-mz_1Z03p8dT07I72viiG&ust=1698828402116000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCNjT6Y3zn4IDFQAAAAAdAAAAABAD",
  //   productName: "Hamred Dress",
  //   price: "35.00",
  //   color: "Blank and White",
  //   badge: true,
  //   des: "Apron dress is a sleeveless dress with a bib and a skirt attached to it just like an apron.",
  // },
];
// =================== PaginationItems End here =================
